# Generated by Django 5.1.3 on 2026-03-19 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startupbackend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startupapplication',
            name='pitch_deck_link',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='description/', verbose_name='Pitch Deck Link'),
        ),
    ]
