# Generated by Django 5.1.3 on 2026-04-26 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startupbackend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=100, verbose_name='Хуудасны нэр')),
                ('content_key', models.SlugField(unique=True, verbose_name='Түлхүүр үг (Slug)')),
                ('text_content', models.TextField(verbose_name='HTML Агуулга')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Сайтын контент',
                'verbose_name_plural': 'Сайтын контентууд',
            },
        ),
    ]
