# Generated by Django 5.1.3 on 2026-04-26 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startupbackend', '0002_sitecontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('startup', 'Startup Founder'), ('investor', 'Investor'), ('admin', 'Admin')], default='startup', max_length=20, null=True),
        ),
    ]
