# Generated by Django 5.1.3 on 2026-04-30 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startupbackend', '0003_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='image',
            field=models.FileField(upload_to='team_members/'),
        ),
    ]
