# Generated by Django 5.1.3 on 2026-04-30 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startupbackend', '0004_alter_teammember_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='industry',
            field=models.CharField(default='Сургууль', max_length=255, verbose_name='Салбар'),
        ),
    ]
