# Generated by Django 5.1.3 on 2026-04-30 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startupbackend', '0005_investor_industry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investor',
            name='industry',
        ),
    ]
