# Generated by Django 5.1.3 on 2026-05-02 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startupbackend', '0006_remove_investor_industry'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='address',
            field=models.CharField(default='Talbai', max_length=500),
        ),
        migrations.AddField(
            model_name='investor',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investor',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
