# Generated by Django 5.1.3 on 2026-05-02 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startupbackend', '0007_investor_address_investor_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StartupRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startup_name', models.CharField(max_length=255, verbose_name='Стартап нэр')),
                ('description', models.TextField(verbose_name='Танилцуулга')),
                ('founder_email', models.EmailField(max_length=254, verbose_name='Имэйл')),
                ('meeting_requested', models.BooleanField(default=False, verbose_name='Уулзалт хүссэн эсэх')),
                ('status', models.CharField(choices=[('pending', 'Хүлээгдэж байна'), ('approved', 'Зөвшөөрсөн'), ('rejected', 'Татгалзсан')], default='pending', max_length=20, verbose_name='Төлөв')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startupbackend.investor', verbose_name='Хөрөнгө оруулагч')),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startupbackend.startup', verbose_name='Үүсгэн байгуулагч')),
            ],
            options={
                'verbose_name': 'Стартап хүсэлт',
                'verbose_name_plural': 'Стартап хүсэлтүүд',
            },
        ),
    ]
