# Generated by Django 5.1.3 on 2026-05-02 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startupbackend', '0008_startuprequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='startuprequest',
            name='founder_email',
        ),
    ]
