# Generated by Django 5.1.3 on 2026-05-02 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startupbackend', '0009_remove_startuprequest_founder_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startuprequest',
            name='investor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests_received', to='startupbackend.investor'),
        ),
        migrations.AlterField(
            model_name='startuprequest',
            name='startup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests_sent', to='startupbackend.startup'),
        ),
    ]
